name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git submodule update
      run: git submodule init && git submodule update
    - name: make
      run: make all
    - name: make runtests
      run: make runtests
